### ISSUE TITLE
 requirements.txt

### ISSUE THREAD

**Issue by bobbybeard427** [oxivanisher/PiPyDailyClock#1]
having a error when entering venv/bin/pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by oxivanisher** [comment]
After you cloned the source with git clone, you have to `cd` into the PiPyDailyClock directory before running the pip command. I.e: `cd PiPyDailyClock`.

**Comment by bobbybeard427** [comment]
gotcha thanks.

**Comment by oxivanisher** [comment]
No worries. Good luck :)

Also as a comment:
This project is not really abandoned, but you are probably the second person after me which uses this and the setup was not testet for several years. I just fixed some problems i found over the last four years, but there might be additional problems with the setup down the road. I don't want to discourage you building it, I find it great when somebody else uses this, but it might be a bumpy road to get to the final destination. :)
